### ISSUE TITLE
About HumanAct12 and other AMASS data

### ISSUE THREAD

**Issue by LinghaoChan** [Mathux/AMASS-Annotation-Unifier#1]
The humanact12 provides datafile in `*.npy`. However, other data in AMASS like CMU end with `*.npz`. Besides, the data in humanact12 is organized in numpy array. The data in other AMASS is organized in a dictionary format with keys: `['trans', 'gender', 'mocap_framerate', 'betas', 'dmpls', 'poses']`. 

I met this error when running `humanml3d.py`.

**Comment by LinghaoChan** [comment]
The main problem is how to calculate the duration of humanact12.

**Comment by Mathux** [comment]
Hello @LinghaoChan, 

Thanks for your issue. I will update the README to explain how to get the ``*.npz`` of humanact12. I did this in [ACTOR](https://github.com/Mathux/ACTOR), by finding the original SMPL fits of [PHSPD](https://jimmyzou.github.io/publication/2020-PHSPDataset), and take the original crops aligned with the humanact12 dataset.

For now, I temporarly updated the repo by skipping them.

**Comment by LinghaoChan** [comment]
Thanks for the reply. The problem was resolved.
